"""add_current_stage_and_gate_status

Revision ID: 80a0d7e49066
Revises: 
Create Date: 2026-10-08 12:11:31.114295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80a0d7e49066'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('current_stage', sa.String(length=32), nullable=True))
    op.add_column('tasks', sa.Column('gate_status', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'gate_status')
    op.drop_column('tasks', 'current_stage')
    # ### end Alembic commands ###
